### ISSUE TITLE
Weapon and Nano potions disappear when killing an enemy

### ISSUE THREAD

**Issue by mclydian** [OpenFusionProject/OpenFusion#119]
After purchasing a nano or weapon potion, and then going to fight an enemy, defeating the enemy results in your potions being removed. Buying at least one nano/weapon potion seems to add all the previously bought potions back to your inventory. Just thought this is something that should be looked into

Example of the potion bug: https://youtu.be/aFEnPcr6W1Y

**Comment by JadeShrineMaiden** [comment]
This bug is due to the packet struct sP_FE2CL_REP_REWARD_ITEM being incomplete when sent. Setting m_iBatteryN and m_iBatteryW would solve it.
