### ISSUE TITLE
Stackable items not handled properly when trading

### ISSUE THREAD

**Issue by gsemaj** [OpenFusionProject/OpenFusion#136]
"when trading, when you drag a gumball or whatever into the trade window, it instead opens up a menu where you can specify the amount, but when you do so, it doesn't take anything away from the stack in your inventory
but you can add items to the trade as many times as you want from that stack
and also they don't stack in the trade slots"

**Comment by Lolbobayouatethesnacks** [comment]
Hmm

**Comment by dongresource** [comment]
Fixed by #192, which is being merged manually.
