### ISSUE TITLE
Floating glitch           bug 

### ISSUE THREAD

**Issue by Lolbobayouatethesnacks** [OpenFusionProject/OpenFusion#146]
Ok so i know you guys brought back fusion fall but there are alot and i mean alot of bugs ok so i got to level 6 and i went into fusion mayor's lair and it was broken and there was no way in or out then i wanted to do a race and the race was just stuck on the same screen so after these problems i decided it would be an amazing idea to do a different mission right  nope i lost connection and the enemies i was attacking disappeared  so i log out then log back in and then my character is all glitch out so i think this is a bug i can fix by logging in and out nope guessed wrong my character is stuck like that for the rest of the game  this is so annoying
it was so hard for me to get a big chill mask i was super lucky to even get one in those pumkin eggs i dont wanna have to start all over again and now the game is saying my character is unknown come on  and this is my first time playing fusion fall i started yesterday i love this game but the bugs gotta go please tell me whats going on. 
![2020-10-29 **(3)](https://user-images.githubusercontent.com/73680462/97657973-97fbf380-1a41-11eb-888e-b9e78eca68f5.png)**

**Comment by Lolbobayouatethesnacks** [comment]
I think i fixed it i had to warp but im STILL STUCK ON THE LOG IN SCREEN WHAT THE HECK

**Comment by JadeShrineMaiden** [comment]
- Fusion lairs (save for the first 12 nanos) are not in yet, dont use them.
- Races are not in yet, dont use those.
- Use /warp 7 8 if you end up somewhere weird.
- Logging in bug should be fixed.

**Comment by dongresource** [comment]
Please use punctuation when typing. Word salad is hard for anybody to read.

This software is a work-in-progress. The public server you're playing on is meant to help us test the game and iron out any bugs before we declare it fully playable.

As Jade has explained, most of the things you pointed out are not bugs; they're functionality we haven't started working on yet.

And don't get too attached to any of your characters or items. We reset the public server's database every once in a while. Again; the public server is meant to test the software as we develop it. Nothing on it is permanent.
