### ISSUE TITLE
and broken glitches

### ISSUE THREAD

**Issue by Lolbobayouatethesnacks** [OpenFusionProject/OpenFusion#147]
Every time i go into mayors lair its closed off can you look into it.
![Screenshot (1)](https://user-images.githubusercontent.com/73680462/97730612-77b44f00-1aaa-11eb-82bd-523078715312.png)

**Comment by CakeLancelot** [comment]
This was already resolved [here](https://github.com/OpenFusionProject/OpenFusion/issues/146#issuecomment-719423305). What you're encountering is not a bug - the lair isn't populated.
