### ISSUE TITLE
Where are the tech wings?

### ISSUE THREAD

**Issue by Lolbobayouatethesnacks** [OpenFusionProject/OpenFusion#148]
Ok so i am doing bens mission and there are no tech wings where are they and please do not cancel this message. This is a bug

![2020-10-30 (1)](https://user-images.githubusercontent.com/73680462/97744950-7ab93a80-1abe-11eb-9ef1-dd5b4c691744.png)

**Comment by CakeLancelot** [comment]
Not a bug.
