### ISSUE TITLE
Enemies not spawning

### ISSUE THREAD

**Issue by TAnthonyGaming** [OpenFusionProject/OpenFusion#151]
I am trying to do som missions but the Tech Wings and doom drones aren't spawning in Genius Grove.

**Comment by TAnthonyGaming** [comment]
Also when I enter Fusion Mayor's lair the quest doesn't update and nothing spawns

**Comment by EthanAnav** [comment]
The dev team is currently working on placing mobs in the overworld. Once they're done with that, they will move on to fusion lairs.

**Comment by TAnthonyGaming** [comment]
Is there somewhere I can follow for news and updates?

**Comment by EthanAnav** [comment]
Any updates will be posted on the discord server.

**Comment by TAnthonyGaming** [comment]
Gotcha!
