### ISSUE TITLE
Mobs Not Showing Up

### ISSUE THREAD

**Issue by EthanAnav** [OpenFusionProject/OpenFusion#152]
I saw that the mobs for Genius Grove have been merged already. But when I started the game, I couldn't see any enemies in that area. I know I have the latest version of the client. Could it be that the mobs for levels 7 or higher have not yet been added to the public server. Please let me know if there is a solution to this.

**Comment by CakeLancelot** [comment]
Merged just means merged into the [tabledata repo](https://github.com/OpenFusionProject/tabledata), the changes will be available on the public server tomorrow.
