### ISSUE TITLE
Controls freeze and camera spins

### ISSUE THREAD

**Issue by Breezeski** [OpenFusionProject/OpenFusion#164]
Was having a smooth playthrough until my controls froze and my camera spun out of control. I couldn't play anymore because it consistently happened any time I closed and reopened the game

**Comment by gsemaj** [comment]
Do you have a controller plugged in, by chance? This is a known issue with the client when there're USB gamepads connected.

**Comment by Breezeski** [comment]
Ohh so we can't play with controllers?

**Comment by gsemaj** [comment]
The client supports controllers, but the build we're using does have that bug. There might be a way to get around it, but I'm not sure. You might be able to find someone on the Discord who knows how to fix it.
