### ISSUE TITLE
Mobs and Teleporters Missing

### ISSUE THREAD

**Issue by ombsik33** [OpenFusionProject/OpenFusion#165]
I haven't had this problem anywhere else, but for Fusion Blossom's second lair in Peachy Creek Estates (part of the Edd's Thingamajig quest line), neither she, the mobs, nor the exist spawn. The only way out of the area is to leave the game.

**Comment by EthanAnav** [comment]
I had this exact same problem, but I used the /warp command to get out of there.

**Comment by gsemaj** [comment]
This is not a bug. Most fusion lairs in the game have not been populated yet. Check the Discord for updates on mob population.
