### ISSUE TITLE
Wilt nano mission broken

### ISSUE THREAD

**Issue by doctorjcsuperfliper** [OpenFusionProject/OpenFusion#167]
The mission does not update your objective after entering the portal for his lair. Also if you warp away while inside you will warp way up high and fall forever while stretching like a rubber band. Quite funny to see but very annoying and only way out is to relog.

**Comment by gsemaj** [comment]
Hi there,

All Fusion lairs in the past have not been populated properly. This means they don't have objective waypoints, mobs, or respawn points. There are some temporary NPCs that the admins throw in, but we still discourage entering the lairs.
For now, you can just use /warp 7 8 to return to Sector V. If you have more questions, please check the FAQ or Tech Support channels on the Discord.

Thanks!
