### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by DampWaffles** [OpenFusionProject/OpenFusion#168]
When creating a new character it will come up with a notification saying "Character Creation Error" then closes the game

**Comment by gsemaj** [comment]
Can you give a couple more details? What's your username? When in the character creation process are you getting the error message? Do you have any other characters on that account?

**Comment by DampWaffles** [comment]
I have a useable character that still opens fine but I tried a couple different times and no matter what you select for name or character after you choose your clothes and hit continue it pops up with a message saying "Selected Character Error" and gives you a box to click ok then it closes the game. My friend just downloaded it and is having the same issue aswell

**Comment by gsemaj** [comment]
Okay, understood. We are trying to track down the issue. What is your username? What is your friend's username? How many characters do you have on your account? Just the one?

**Comment by DampWaffles** [comment]
I have 3 Characters, The two that work are Damp Waffles, Vegeta JR and the one that didn't work was Bulma Briefs
![failed_game_screen](https://user-images.githubusercontent.com/75053540/100300594-fc847280-2f5b-11eb-83e6-ca9301554a2c.PNG)

**Comment by DampWaffles** [comment]
We found out that if you hit continue as soon as you enter the character creation tab it will allow you to enter the game

**Comment by gsemaj** [comment]
Hey, thanks for the info. Turns out our latest database update accidentally made it impossible to make female characters (oops).
We'll patch this shortly. Thanks again.
