### ISSUE TITLE
Issue with Fizzy Rox and Roll

### ISSUE THREAD

**Issue by DampWaffles** [OpenFusionProject/OpenFusion#169]
When you play through the mission and get to the part where you enter the fusion portal it will let you go inside but the mission won't update and will say Enter Fusion Portal. I reset the game a couple times attempting to fix the issue but it did not work.

**Comment by gsemaj** [comment]
This is not a bug. All fusion lairs in the Past zone are not properly populated. They are not ready for play. This information, amongst other updates, can be found on our Discord. Alternatively, you can keep up with the commit history and project boards on here. Please check the Discord before asking questions on here in the future.
