### ISSUE TITLE
Billy Nano Mission Error

### ISSUE THREAD

**Issue by EthanAnav** [OpenFusionProject/OpenFusion#173]
I was doing the Billy Nano mission, but when I got to the Fusion Portal, I couldn't warp out of it and the mission log didn't update. Also, Billy's NPC was missing. Is this something that you can fix when you get the chance?

**Comment by gsemaj** [comment]
You are not the first person to ask this, but we've made it clear on multiple occasions that _**no fusion lairs in the Past zone**_ are guaranteed to work right now. We haven't even reached the stage where we will properly populate them, as they are last on the todo list. They will not be properly playable until we say they are ready. **Please** do not continue to report missing features as bugs, and check the official Discord if you have any questions before posting any issues on the GitHub repository.
