### ISSUE TITLE
Linux people? 

### ISSUE THREAD

**Issue by fabianmendes** [OpenFusionProject/OpenFusion#175]
Is there any possibility to create a version for Linux?

Not using wine

**Comment by CakeLancelot** [comment]
The OpenFusion server runs on Linux natively. The FusionFall client/webplayer however, was only released for Windows and Mac. 

Creating a native Linux client is outside the scope of this project.

**Comment by DarthMDev** [comment]
what about a mac client then?

**Comment by CakeLancelot** [comment]
Apple has discontinued support for 32 bit apps as of MacOS 10.15 Catalina. So this would not be possible.
