### ISSUE TITLE
Dexter Guide Mission: Tech Meets Magic

### ISSUE THREAD

**Issue by Art3misForever** [OpenFusionProject/OpenFusion#193]
I ran into an issue doing the Tech Meets Magic Guide Mission that involves climbing the Monkey Mountain Infected Zone. The Ancient Monkey Totems aren't appearing as interactable/quest objects, making it currently impossible to complete the quest. 

I hope this was helpful, and pray to the gods its fixed soon, but please, take your time, no rush at all!
 
Thanks!

**Comment by CakeLancelot** [comment]
This issue is due to the irregular shape of the IZ. Most Infected Zones are just a rectangle and so it's easy to automatically move everything to the right instance, but we may have missed some of these special ones.

I'll keep this open to let you know when it's fixed. Thanks for the report.

**Comment by Art3misForever** [comment]
You're welcome, absolutely no problem.

**Comment by CakeLancelot** [comment]
This should be fixed now
