### ISSUE TITLE
Ability to set account level at runtime

### ISSUE THREAD

**Issue by kodxana** [OpenFusionProject/OpenFusion#194]
Is there any way to set admin user on self hosted server and change users ability to use certain commands?

**Comment by CakeLancelot** [comment]
Currently, you can do this by editing the database file with something like [DB Browser for SQLite](https://sqlitebrowser.org/). I understand this may not be ideal for most users, so I'll keep this open as a feature request (editing access level at runtime).

**Comment by dongresource** [comment]
Note also that every user has GM privileges by default on local servers unless you change the default access level in the config file.

**Comment by kodxana** [comment]
What are exaclly settings in config file cause I do not see them.

**Comment by kodxana** [comment]
nvm found it now people are set to 99
