### ISSUE TITLE
Game shows on both displays when put in fullscreen from non-primary display

### ISSUE THREAD

**Issue by Janterra** [OpenFusionProject/OpenFusion#195]
When you are running the game on a secondary(2nd, 3rd, etc.) display and use the fullscreen button in game to switch to fullscreen, the game goes fullscreen on the primary display and a frozen view of the game remains on the secondary display. Unknown if this issue is able to be recreated by others.
![Screenshot of the issue.](https://user-images.githubusercontent.com/25830877/104146228-017c7480-5398-11eb-9f09-6ca3d5971d95.jpg)

**Comment by dongresource** [comment]
OpenFusion is a server development project. We are not working on the client, thus we cannot fix these types of issues.
