### ISSUE TITLE
White screen when clicking "register"

### ISSUE THREAD

**Issue by Sollace** [OpenFusionProject/OpenFusion#197]
I just found this project recently and was curious to see what it's like since I'd never had the chance to play FusionFall when it was still running.

I selected a server and loaded it up, then it goes to a character creation screen where I had to sign in. Don't have an account yet, so I clicked on "register" hoping it would go to a "new account" screen, but nothing happened.

I then clicked register again and it soft crashed. :/

![image](https://user-images.githubusercontent.com/6429283/104810028-aebd1580-57fa-11eb-8430-ad28ccd0b99e.png)

**Comment by Sollace** [comment]
Same thing seems to happen when clicking "manage account"

**Comment by Sollace** [comment]
Using the 1.3 release btw.

**Comment by gsemaj** [comment]
The register button currently doesn't function as OpenFusion uses server-specific accounts (please see the README on the main GitHub page). Whenever you want to make a new account, you just login with the username and password that you would like to use, and enter those same details in every time you want to use that account.

If you have more questions, make sure you read the README and FAQ on our Discord, and if you're still stuck, we have a tech support channel on there as well.
