### ISSUE TITLE
Camera keeps spinning when using a controller

### ISSUE THREAD

**Issue by grafeon** [OpenFusionProject/OpenFusion#206]
When I connect my Dualshock 4 controller, the camera keeps spinning to the right, the game is also not letting me configure any buttons, however, I can walk around using my controller so I know it is compatible.

**Comment by CPunch** [comment]
This issue is related to the FusionFall client, we have no rights on that codebase and cannot release a patch for this issue. 

However a workaround has been shared in the Discord FAQ channel:
```
# My camera spins around uncontrollably once I get ingame.

Try unplugging any controllers that you may have connected: while Fusionfall does have support for them, it is limited and can be glitchy depending on the type of controller.

AND/OR

Disable DPI scaling: Right click your desktop and choose "Display Settings", in the window that opens, scroll down to "Scale and layout" and make sure that "Change the size of text, apps, and other items" is set to 100% before launching the game.
```
