### ISSUE TITLE
The classic "Unity Player Not Updated" error.

### ISSUE THREAD

**Issue by AndyK1125** [OpenFusionProject/OpenFusion#209]
Tried to download Unity, still the same message. Help!

**Comment by CakeLancelot** [comment]
Fusionfall uses a specific Unity Web Player version that cannot be installed from Unity's website. Normally, installation of the Web Player should be done automatically, but you can try re-running the installation by double clicking `installUnity.bat` in the `utils` folder to see if that fixes it.

For further user support regarding the Fusionfall game client, please use the tech-support channel in the [OpenFusion Discord](https://discord.gg/ctdWgmm5sW).
