### ISSUE TITLE
Disable case-sensitivity on Login column

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#211]
As it stands, the `Login` column in the `Accounts` table is case sensitive. This leads to some unwanted interactions when logging in:  the user would capitalize one or more letter of their already existing username and create a new account. 

For this, a database migration will be needed to change the column to `COLLATE NOCASE` - but there may also be duplicate accounts that need to be merged or deleted. We should be able to provide some sort of script to solve the majority of these issues. 

Note: be sure to modify all known public server owners so that they can run the script and upgrade smoothly.

**Comment by dongresource** [comment]
Implemented in 2eb64540d1e0e0832512ef691d1c509736339144.
