### ISSUE TITLE
i need a guide on how to open a port properly for a private server for friends.

### ISSUE THREAD

**Issue by zanezonair** [OpenFusionProject/OpenFusion#212]
i have a rough idea of how to open ports but i need to know what ip adress i need to enter in. as i dont know weather to enter in my ip or not  same for local port as i dont know what goes there
i would like to play fusion fall again with my friends.
any help would be very appriciated.
![Screenshot 2021-04-30 010942](https://user-images.githubusercontent.com/38980540/116655471-c3a85980-a950-11eb-8c80-baeed49bba65.png)

**Comment by CakeLancelot** [comment]
You'll need to change the range to cover both 23000 (login) and 23001 (shard). For private IP address, that would be the local address of the computer you're hosting on. One way to find this is by typing `ipconfig` in a command prompt - there are other methods as well, google is your friend.

For further user support, please use the tech-support channel in the [OpenFusion Discord](https://discord.gg/ctdWgmm5sW). The issues page on this repository is mainly intended for developers to report issues with the codebase of the server itself.

**Comment by zanezonair** [comment]
thank you. your info got it to work perfectly.
i really didnt want to join then leave a discord server to fix one issue.
anyways thank you a bunch. now me and my friends can play together.
