### ISSUE TITLE
Don't fear the reaper (part 4 of 4) bug

### ISSUE THREAD

**Issue by Teoshx** [OpenFusionProject/OpenFusion#219]
Don't know if anyone else has had this issue, but in Don't fear the reaper part 4, after I use the device on the mine cart and enter the fusion portal, the mission doesn't get past "defeat fusion grim" after I've defeated him. I've realoaded, refreshed, killed him and every single simian spawn about ten times now. Has anyone else had this issue? Pls help

**Comment by gsemaj** [comment]
I'm being told this is a known tabledata ID mismatch issue. This should be fixed soon. Thanks for the report.
