### ISSUE TITLE
Failed to download data file

### ISSUE THREAD

**Issue by MePersonMan** [OpenFusionProject/OpenFusion#221]
I'm new to the project, I just got interested after reading some comments after retro got shutdown so any trace of help would be greatly appreciated.
Following the steps provided, downloading and extracting all the files I could find, I can't seem to enter the game. I open the client and select one of the default servers, but instead of being prompted to log in I get an error screen.
"Failed to download data file" for when I select Original and "Failed to update Unity Web Player" when Academy is selected. 
I've updated Unity to the best of my knowledge but Idk if I'm missing something.
I might just be an idiot but I need some help here

**Comment by gsemaj** [comment]
Welcome to the community!!
As crazy as the timing is, the servers that typically host the game assets are currently down (they went offline a few days ago). We are monitoring the situation and may push a client update with a workaround if the servers don't come back up soon.
Thanks!!
