### ISSUE TITLE
UI issue in Academy final mission

### ISSUE THREAD

**Issue by wwardaww** [OpenFusionProject/OpenFusion#230]
Hi, there is a hidden checkbox bug in the teleport station.
in the red circle, there is a hidden checkbox. if you don't click, you won't able to complete the mission.
This is a required mission so you can not enter the game without the clicking hidden check box
[HERE](https://www.youtube.com/watch?v=YtPiFAoVe20) is the video of the original game

![bug](https://i.imgur.com/wmuYxT7.png)

**Comment by dongresource** [comment]
Yeah, we're aware of that one. It's a client-side bug that's triggered by your system language being set to Turkish (and possibly some others?). There's also been issues with some mission text showing up red in the same scenario.

Our servers run unmodified clients from the original game, so we can't fix this type of problem. Luckily the only missions with optional rewards like that are in the early Academy area and nowhere else. The recommended workaround is to change your system language to US English while playing the game if it bothers you.
