### ISSUE TITLE
Crashing on Wraping

### ISSUE THREAD

**Issue by wwardaww** [OpenFusionProject/OpenFusion#231]
![image](https://user-images.githubusercontent.com/12273655/141005612-b1771d70-3933-4a4a-ab53-daecdb3ec049.png)

The Game crashing on wrapping (by portals, monkeys, etc.)

**Comment by dongresource** [comment]
Yes, that's a well-known issue with the client when playing the Academy build. It happens significantly less if you disable the in-game music or if you play on the Original server. There's nothing we can do about it on our end.
