### ISSUE TITLE
Clients stops working

### ISSUE THREAD

**Issue by Tabris666** [OpenFusionProject/OpenFusion#233]
Well i grabbed this because i wanteed to test fusionfall yet after starting the client it get stuck on the accessing screen and stops.
Does this need the original fusionfall client,or this download the fusionfall.
If it needs the client what is the place to post the files,i grabbed the game just in case and is a bunch of resourcefiles but no idea the place i should put them.

**Comment by gsemaj** [comment]
You don't need the original game client or resources. Make sure you're downloading OpenFusionClient v1.4 either through the installer or the standalone zip from our [Releases page](https://github.com/OpenFusionProject/OpenFusion/releases/tag/1.4).

If that doesn't work, provide more info on the client you're using and what server you're trying to connect to.

Thanks!

**Comment by Tabris666** [comment]
I'm using latest client version from the releases page,currently using Windows 64 bit,AMD 4 core 2.6 GHZ (8 threads),8 GB ram,SSD hd.
i tried connecting to the normal public server available,gets stuck infinite loading then crash no data is downloaded

**Comment by gsemaj** [comment]
Those specs look fine. It sounds like something might be blocking the Unity Web Player from initializing. Regardless, this is a client issue and not a server one, so I would recommend asking for help in the Tech Support channel on our Discord server.
