### ISSUE TITLE
Nano candies

### ISSUE THREAD

**Issue by carpengui** [OpenFusionProject/OpenFusion#234]
Overall, this is a minor nit:  pressing 'C' will sometimes feed candies to a Nano to renew their energy, but sometimes it doesn't work... probably more "doesn't work" than "does work".  I've been struggling to find a pattern to help find the source of this, but... not so far.

**Comment by gsemaj** [comment]
This could either be a client or server issue. Note that you can only use your nano potions if you have a nano out (active) and you haven't used any potions in the last second. (Obviously, this doesn't work if you don't have any nano potions at all.)
Also worth noting that the conversion rate is 1 potion per 1 stamina point, so you'd need 150 potions for a full heal. If you're using very few potions, you might not notice a difference at all.

With that information, see if you can try and reproduce the bug consistently and let us know if you find anything.

Thanks!

**Comment by carpengui** [comment]
I'm good with closing this.
