### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by simsim1997** [OpenFusionProject/OpenFusion#235]
So, I have just downloaded the version 1.4 and tried to log in to my account. It's been a few months since the last time I used OpenFusion, so I'm not quite familiar with the new updates. However, I seem to have trouble logging into my account. I'm certain that my password is correct and I'm also sure that the account exists because I get the error message "The ID and the password you have entered do not match." That means that my account still exists, right?
Has there been any resets of the account during the release of the last update? Has anyone else had this problem? What I find very strange is that I'm almost certain that the account exists, otherwise it would just be created automatically. I'm a 100% sure that my password is correct since I've written it down. However, I still get the error.
I really really want to access the account since I've made quite the progress and it would be nice to continue from where I left off.

Thank you so much everyone for your hard work, and OpenFusion is just an amazing game! Also, thank you for anyone who is able to help!

**Comment by gsemaj** [comment]
Thank you for the kind words :)
We haven't had a reset in the last 12 months, so you're right in saying the account still exists. One of the mods on our Discord server (link in the README) would be more than happy to help. Just ask in the tech support channel.
