### ISSUE TITLE
Problem with in-game resolution

### ISSUE THREAD

**Issue by Lorafen223** [OpenFusionProject/OpenFusion#236]
I'm trying to set FusionFall gamescreen to 2400x1080 but it jumps from full-screen to windowed and after I change the game to full-screen resolution ends up as "browser". There is no way to have 2400x1080 in full-screen mode. My system resolution is set to 2400x1080 In case if it would be needed to be clarified.

**Comment by gsemaj** [comment]
Unfortunately, this is a client issue and not a server one, so there's nothing we can do about it for now. The reality is that the game is old as dirt and doesn't play nice with large resolutions. You can either play in windowed mode and deal with the tiny UI scale or play full screen at a lower res. Sorry :(
