### ISSUE TITLE
Not Rejoining Game at Respawn Point

### ISSUE THREAD

**Issue by XenonFiber** [OpenFusionProject/OpenFusion#252]
I may be misremembering after all these years, but I feel pretty certain that the original game would place you at the nearest respawn point when logging back in, not exactly right where you left off.

Could anyone else confirm this?

-- Freya Raccooncat (she/her)

**Comment by CakeLancelot** [comment]
This is not present in the original game, if you have a vehicle you can keep up with the cars but you can't stand still on them without sliding off.

Source: https://www.youtube.com/watch?v=CxUpuMk9wbM

**Comment by CakeLancelot** [comment]
Appearing where you logged out upon logging back in is intended behavior, unless you log out in an IZ or infected zone (in which case you will be placed at the exit).

Source: https://www.youtube.com/watch?v=bXmxhGgkn5E&t=57
