### ISSUE TITLE
Not Maintaining Inertia on Hovercars

### ISSUE THREAD

**Issue by XenonFiber** [OpenFusionProject/OpenFusion#253]
This is another discrepancy from memory, but in the original game, I feel like it was entirely possible to hop onto the top of one of the world's looping hovercars and go for a ride. It would maintain your inertia for as long as your feet were in contact with the roof, just like the bus does (at least until changing directions, at which point you'd (usually?) get thrown off).

-- Freya Raccooncat (she/her)

**Comment by CakeLancelot** [comment]
This behavior is not present in the original game, if you have a vehicle you can keep up with the cars however you can't stand still on them without sliding off.

Source: https://www.youtube.com/watch?v=CxUpuMk9wbM
