### ISSUE TITLE
There may be a trojan imbedded

### ISSUE THREAD

**Issue by ifly1234** [OpenFusionProject/OpenFusion#254]
Whenever I try and connect to the servers on both clients my antivirus pops up. it alerts saying an intrusion attempt from the game's server IP has been stopped. The name for the trojan it gives is Trojan.Nancrat Activity 2. At the same time this message is delivered on my antivirus the game delivers a message saying, "network close". What is the fix for this?

**Comment by CakeLancelot** [comment]
This is a known issue with Norton and other similar anti-virus programs, and is a false positive. 

Unfortunately there isn't anything we can do to fix this on our end. To fix the network close issue that you're having, you will either need to [add an exception](https://support.norton.com/sp/en/us/home/current/solutions/v3672136) to your AV program, or disable the firewall while playing the game (you can turn it back on afterwards).
