### ISSUE TITLE
Accessing Screen

### ISSUE THREAD

**Issue by StormGaming2020** [OpenFusionProject/OpenFusion#255]
I seem to have an issue with Unity Web Player. When I just used the games version, it said it wasn't installed. When I used the recent public version, everything was fine but it would stay on the Accessing Screen after choosing which server.

**Comment by OsirisOfDevils** [comment]
Having same issue after choosing a server it judt goes to the acessing screen and stays there. Any fixes yet?

**Comment by StormGaming2020** [comment]
Okay, I am at a Trade School, and it has something to do with the Internet they have here. So, the only way for me to use OpenFusion version, or even the Retrobution Fusionfall, I need to use a VPN. I'm using a FREE VPN, known as PaladinVPN. Doesn't seem to hace any subscriptions needed even.
