### ISSUE TITLE
unity web player version

### ISSUE THREAD

**Issue by xmrshoot** [OpenFusionProject/OpenFusion#261]
![image](https://github.com/OpenFusionProject/OpenFusion/assets/129559513/ae37ac7e-9b9e-4e92-971a-ae606af0787f)
idk what version to download to work

**Comment by CakeLancelot** [comment]
Hi,

The Unity Web Player version used is a custom version made by CN. It should've been installed automatically installed when starting the client. It appears that you may have installed a different version of the Web Player at some point and overwrote it.

I would recommend downloading the [latest beta of the client](https://cdn.discordapp.com/attachments/745462497322205235/1073316022616068127/OpenFusionClient_Setup_1.4.1.exe) (1.4.1), which will automatically repair the Web Player installation if needed, along with providing many other bug fixes.

If you run into any further issues, feel free to drop a message in our [Discord server](https://discord.gg/DYavckB) (the Github page is more meant for developers).

Thanks!
