### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by BenLikestoPlayFusionFall** [OpenFusionProject/OpenFusion#263]
OK, just wondering, but do you think it's possible to port OpenFusion to Mac? Yes, I know OpenFusion's on Bluemaxima's Flashpoint, but I want to play online, I know it's possible since FusionFall could run on Mac back in the day, please can you port this project on Mac? Thanks.

**Comment by JadeShrineMaiden** [comment]
Hi Ben,

Current issue with Mac support is that native Mac architecture does not support base Fusionfall anymore, while yes it used to run on older macs and still will given that you run it with the much older operating system (not recommended) and device, this is not the case with newer Macs. 

I am not saying it is impossible to port Fusionfall to newer Macs someday but to do so is a gargantuan effort that isn't within our scope or powers as of currently. Your only workaround for now is that you virtual machines (parallels, bootcamp, vmware etc.) to emulate windows on your device.
