### ISSUE TITLE
Docker image in Docker Hub?

### ISSUE THREAD

**Issue by Juansecu** [OpenFusionProject/OpenFusion#270]
Is there a way to install an official OpenFusion Docker image from a registry like Docker Hub?

If not, do you plan to release it?

**Comment by CakeLancelot** [comment]
This should've been pushed with the 1.6 release, however there seems to be some error regarding the arm64 build. I will see if I can investigate sometime this week.

**Comment by Juansecu** [comment]
> This should've been pushed with the 1.6 release, however there seems to be some error regarding the arm64 build. I will see if I can investigate sometime this week.

Alright! Let me know if I can help you with anything.

**Comment by CakeLancelot** [comment]
This has been resolved and there should now be a image available on Docker hub. 

However the build action can take a while, so for now it will only be triggered with each release, or manually if we need to push important hotfixes.

Thanks for all the assistance in getting this up and running!

**Comment by Juansecu** [comment]
My pleasure, @CakeLancelot!
