### ISSUE TITLE
Implement trade cancel packets

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#278]
Copied from the Discord:

Gent — 12/09/2023 9:26 AM
noticed while working on RustyFusion that we aren’t handling P_CL2FE_REQ_PC_TRADE_OFFER_CANCEL, which is what the client sends if the player is in combat, shopping, etc. and they get a trade offer. Response packets do exist and it looks like they are handled clientside (with UI even) so I might put up a PR for that too.

**Comment by yungcomputerchair** [comment]
I can churn this out pretty quickly.
