### ISSUE TITLE
Docker UX issues

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#292]
There are still a few issues that I would like to address regarding Docker:

First of all the UX is somewhat confusing. For example: if you use Docker Desktop and search for our image, the resulting download will be missing all the port/file mounts that the docker-compose.yml normally sets up. One way to fix this would be to specify in our Dockerhub description/README to specifically use `docker compose` , then make sure our Dockerhub URL is specified in the yml like so:
```
image: openfusion/openfusion:latest
```
This will make it to where if you run `docker compose up` and have an internet connection, it will automatically grab an image instead of compiling from scratch.

Another thing is that while the server starts up without issue, whenever I connect I get a sandbox related crash. The easiest solution I see is probably just to disable the sandbox for Docker builds, but I'm open to suggestions.

Lastly, whenever the ARM64 build was pushed, it seems to have overwritten the AMD64 build. This should be a simple configuration-related fix.

**Comment by Juansecu** [comment]
@CakeLancelot Here you have a README for Docker HUB:

<p align="center"><img width="640" src="https://raw.githubusercontent.com/OpenFusionProject/OpenFusion/master/res/openfusion-hero.png" alt="OpenFusion Logo"></p>

<p align="center">
    <a href="https://github.com/OpenFusionProject/OpenFusion/releases/latest"><img src="https://img.shields.io/github/v/release/OpenFusionProject/OpenFusion" alt="Current Release"></a>
    <a href="https://github.com/OpenFusionProject/OpenFusion/actions/workflows/check-builds.yaml"><img src="https://github.com/OpenFusionProject/OpenFusion/actions/workflows/check-builds.yaml/badge.svg" alt="Workflow"></a>
    <a href="https://hub.docker.com/repository/docker/openfusion/openfusion/"><img src="https://badgen.net/docker/pulls/openfusion/openfusion?icon=docker&label=pulls"></a>
    <a href="https://discord.gg/DYavckB"><img src="https://img.shields.io/badge/chat-on%20discord-7289da.svg?logo=discord" alt="Discord"></a>
    <a href="https://github.com/OpenFusionProject/OpenFusion/blob/master/LICENSE.md"><img src="https://img.shields.io/github/license/OpenFusionProject/OpenFusion" alt="License"></a>
</p>

OpenFusion is a reverse-engineered server for FusionFall. It primarily targets versions `beta-20100104` and `beta-20111013` of the original game, with [limited support⁠](https://openfusion.dev/docs/reference/fusionfall-version-support/) for others.

For full documentation regarding setting up or contributing to the OpenFusion project, please visit our [Github repo⁠](https://github.com/OpenFusionProject/OpenFusion) or [website⁠](https://openfusion.dev/).

## Running

### Using Docker CLI

For running the application server using the Docker CLI, it is necessary to expose the following ports through option `-p`:

- `23000` - For authenticating users (Required)
- `23001` - For sharding (Required)
- `8003` - For monitoring (Optional)

And mount the following files through option `-v`:

- `/usr/src/app/config.ini` for the server configuration file (Optional)
- `/usr/src/app/database.db` for the application database (Optional)
- `/usr/src/app/tdata` for game data (Required)

Said this, you would use the following command for running the server application:

```shell
# Windows
> docker run -dp 23000:23000 \
        -p 23001:23001 \
        -p 8003:8003 \
        -v path\to\config\file\in\host\machine\config.ini:/usr/src/app/config.ini \
        -v path\to\database\file\in\host\machine\database.db:/usr/src/app/database.db \
        -v path\to\tdata\folder\in\host\machine:/usr/src/app/tdata \
        --name openfusion \
        openfusion/openfusion

# MacOS / Linux
$ docker run -dp 23000:23000 \
        -p 23001:23001 \
        -p 8003:8003 \
        -v path/to/config/file/in/host/machine/config.ini:/usr/src/app/config.ini \
        -v path/to/database/file/in/host/machine/database.db:/usr/src/app/database.db \
        -v path/to/tdata/folder/in/host/machine:/usr/src/app/tdata \
        --name openfusion \
        openfusion/openfusion
```

### Using Docker Desktop

For running the application server using Docker Compose, you can use the [Docker Compose file](https://github.com/OpenFusionProject/OpenFusion/blob/master/docker-compose.yml)
provided in our repository, but applying the following changes:

1. Remove the `build` property from the `openfusion` service.
2. Change the `image` property from the `openfusion` service to `openfusion/openfusion`

Once you have applied the below changes, you can run the following command to get the application server running using Docker Compose:

```bash
$ docker compose up -d
```

**Comment by Juansecu** [comment]
@CakeLancelot I just checked the results of the **Push Docker Image** action, and found the push of the tag **1.6** failed.

As a suggestion, you should erase the tag _master_ from Docker Hub, optimize the Dockerfile and try to run the push of tag 1.6 again.

**Comment by CakeLancelot** [comment]
Juan fixed the issue with the builds being overwritten and I made the tweaks I wanted to the Dockerfile and docker-compose.yml, now just need to put the finishing touches on the Dockerhub README and we can close this out.

**Comment by CakeLancelot** [comment]
This has been completed, closing.
