### ISSUE TITLE
Create project board / task list

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#36]
In order to prevent conflict between who is working on what, a task list or project board should be created. This could be done with the project tab, individual issues per feature, etc.

**Comment by dongresource** [comment]
Agreed. Are you volunteering for that responsibility? :stuck_out_tongue:

**Comment by CakeLancelot** [comment]
I'd be fine with with volunteering, but currently don't have permissions to do anything in the Projects tab. So I would either need that or do it via smaller issues and/or task lists.

**Comment by CakeLancelot** [comment]
I've created a project board to start tracking the implementation of features that were in the original game. Enhancements and bug fixes can continue to be posted in the Issues tab. Leaving this issue open in case we want to create another project board for refactors, etc.

**Comment by CakeLancelot** [comment]
Closing this as the feature tracking board seems to be working well enough, if the need arises to create another board or make tweaks a new issue can be created.
