### ISSUE TITLE
Re-send NPCs after warping

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#38]
When using an dexbot/lair entrance to teleport or when using /goto, NPCs will not back show up until you leave the area and come back.

![2020-08-24_22-45-47](https://user-images.githubusercontent.com/5341136/91120584-9ede4280-e65b-11ea-9b63-059066e63234.gif)

**Comment by dongresource** [comment]
Fixed. Will submit PR after my pending one is merged.

**Comment by CPunch** [comment]
fixed in latest merge
