### ISSUE TITLE
Dying doesn't reset nano health

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/OpenFusion#44]
Upon dying, the health/energy of your nanos will be set to zero - due to this, you can no longer summon them. While using the /nano_equip command again does fix this, the nano health/energy should still be reset to full upon respawn.

![image](https://user-images.githubusercontent.com/5341136/91267848-d15e6d00-e739-11ea-8ff3-d722374621c9.png)

**Comment by Frizy0** [comment]
A little note: Nanos health shouldn't be reset to full, it should reset to half of their health as can be seen in this video: https://youtu.be/OCoS397A0gU?t=66

**Comment by gsemaj** [comment]
I can look into this if it's not being worked on already.
