### ISSUE TITLE
Network error inmiddeadly after going in numbuh two's plane

### ISSUE THREAD

**Issue by ToonyTube** [OpenFusionProject/OpenFusion#76]
everything worked fine until i was almost done with the buttercup mission when i press to talk with Numbuh 2 the animation worked fine but it seemed to freeze? after some minutes or seconds it gives me an in-game popup saying "Network error"

**Comment by CakeLancelot** [comment]
This is a known bug when completing the tutorial normally. Skipping the tutorial by pressing the tilde key (`~) should get around this.

**Comment by GhostKing2099** [comment]
I just downloaded the game and skipped the tutorial, still have the network error issue.
