### ISSUE TITLE
Project re-licensed to regular MIT

### ISSUE THREAD

**Issue by Raymonf** [OpenFusionProject/OpenFusion#9]
The project originally used a joke license called the "OpenFusion MIT except Malorn License". It was never meant to be permanent, regardless of how annoying Malorn and his supposed leaks or whatever the hell he calls his """"work"""" may be.

I've already went ahead and changed the license to the regular MIT license. As such, every commit after `7f8e7dfa1ccd3fa406208b3239d8831d3c7d39e0` is _technically_ under regular MIT, unless a contributor decides that they do not want their work to be licensed under regular MIT. In that case, I'll pull out their code and make a note here about which commits are not okay to use.

I'd like to just have every contributor confirm whether they're okay or not okay with this change. To the contributors of the project, could you just comment something that either gives us a green or red light on this change?

(Yeah, I should have made this issue first...)

~~@CPunch~~ ~~@dongresource~~ ~~@JadeShrineMaiden~~ @Eperty123 ~~@CakeLancelot~~

**Comment by CPunch** [comment]
yes

**Comment by CakeLancelot** [comment]
Yeah, that's fine by me.

**Comment by dongresource** [comment]
I hereby consent to the code I've contributed to this project being re-licensed from a faux-MIT license to the proper MIT license.

**Comment by JadeShrineMaiden** [comment]
consented, sorry for the late message

**Comment by Eperty123** [comment]
Cool by me
